FORMAT: 1A
HOST: https://api.paysafe.com/reporting/v1/

# Reporting API Reference

Paysafe's Reporting API provides endpoints for querying and generating reports based on your payments history. You can extract the data to a report in .csv format. You can retrieve the following reports using our API:

* Chargeback (monthly_chargeback_report)
* Onboarding (onboarding_report)
* Onboarding Holds (onboarding_holds_report)
* Onboarding Pending (onboarding_pending_report)
> **Note:** The ids of each report are in paranthesis. 

For a detailed description on the four types of reports, refer to the Reporting API Getting Started.... (TBD)

# Prerequisites
<a name="prereq" title="Prerequisites"></a>

Below are the prerequisite steps for merchant onboarding:

1. The partner must contact the account manager to set up the account.
2. Once the account is set up, Paysafe integrations team will provide authentication credentials.

### Scope and Restrictions

* All the API's are RESTful.
* The Direct Merchants and Platform Partners who possess the Shared API key will only be able to use this API.
* Onboarding reports should be accessed only by Partners.

<a name="apikey" title="Authentication"></a>
# Authentication 

To use the Paysafe REST API, Paysafe must first set up its system for you 
and then provide an API key. Your API key looks something like this:
 * Key ID – PartnerXYZ
 * Key Password – B-tst1-0-51ed39e4-312d02345d3f123120881dff9bb4020a89e8ac44cdfdcecd702151182fdc952272661d290ab2e5849e31bb03deede7e

The case-sensitive API key is sent using HTTP Basic Authentication. To use HTTP Basic Authentication, you must send the API key credentials using the Authorization header with every request. The Authorization header is constructed as follows:
 1. Combine the Key ID and Key Password into a string separated by a colon, for example: “Key ID:Key Password”.
 2. The resulting string literal is then encoded using Base64.
 3. The authorization method and a space (that is, “Basic”) are added before the encoded string.

For example, using the Key ID and Password examples above, the header is formed as follows:

`Authorization: Basic
UGFydG5lclhZWjpCLXRzdDEtMC01MWVkMzllNC0zMTJkMDIzNDVkM2YxMjMxMjA4ODFkZmY5YmI0MDIwYTg5ZThhYzQ0Y2RmZGNlY2Q3MDIxNTExODJmZGM5NTIyNzI2NjFkMjkwYWIyZTU4NDllMzFiYjAzZGVlZGU3ZQ==`

For additional details, refer to [Authentication](https://developer.paysafe.com/en/rest-apis/reference-information/important-integration-concepts/authentication/).

**Note:** Your Production API key will be different from your Test API key. Contact your account manager for details. You must keep your API keys safe and ensure that they are used appropriately for your needs.

# Getting Started

Click [here](https://developer.paysafe.com/en/rest-apis/platforms/account-management/typical-api-calls/) for details on Reporting API..... (TBD)

# Going Live
 
Once you are satisfied with your integration to the Test environment, you must repeat the configuration changes made to your Test account on your Production account.

> **Note:** You cannot use your Test credentials to process transaction requests in the Production environment.

### Go Live Checklist
1. You must have a production account and an Onboarding Config ID for your production account.
2. You must have the API Keys for the production environment.
3. You must use the Production URL for your API calls.

**Note:** For items 1, 2, & 3 reach out to your account manager or <integrations@paysafe.com> for any issues.

### Production URL
To process live requests with Paysafe, use the following Production URL:

`https://api.paysafe.com/reporting/v1/`

For example:

`https://api.paysafe.com/reporting/v1/report-requests`

# Error Summary

| HTTP Status | Error Code    | Error Message |Description |
|-------------|---------------|-------------  |------------|
|400                |5068           |An invalid request was submitted.|Either your request is missing a mandatory field or the value of a field does not match the format expected.|
|400                |5269           |Entity not found.|Report doesn't exist with given id.|
|400                |5042           |Invalid merchant reference.|You have not subscribed to this report, please create a new subscription.|
|400                |5270           |Unauthorized access.|The credentials do not have permission to access the requested data.|
|401                |5068           |Unauthorised Request.|Unauthorised Request.|
|403                |5068           |The source you requested is forbidden.|The source you requested is forbidden.|
|404                |5068           |Not Found.| Not Found.|

# Webhooks
<a name="webhooks" title="Webhooks"></a>
A Webhook is an HTTP callback that is triggered when an event takes place. 

> **Note:** To receive webhooks from Paysafe, you must create a callback URL to receive the webhook that is triggered. 
Paysafe will attempt a maximum of three times to deliver the report if your webhook is unreachable. You are responsible for ensuring its continued availability.

You will receive the following webhook payload for the specified callback URL. The payload contains a link from where you can download the report. The following payload sample illustrates this: 

```
{
  "report": {
    "requestId": "6cd9b563-65fa-460e-9052-c823d2d3f331",
    "status": "SUCCEEDED",
    "files": [
      "https://paysafe-ss-analytics-876548798765-ca-central-1-reports-qa.s3.ca-central-1.amazonaws.com/reportOutputs/2020_11/6cd9b563-65fa-460e-9052-c823d2d3f331/c31f2940-a47a-4130-9e4b-8d2e74ed953b.csv..."
    ]
  }
}
```
> **Note:** You can download the reports for a pre-defined period (up to seven days). 
```

## Verify That the Service Is Accessible [GET /monitor]
<a name="verifyservice" title="Verify Service"></a>

This call returns a status of READY if the API is available.

+ Response 200 (application/json)

  + Body
    
            {
                "status" : "READY"
            }

# Group Subscriptions

## Subscriptions [/report-configs/{reportId}]

### Subscribe to a Report [POST /report-configs/{reportId}/subscriptions]
<a name="subscribereport" title="Subscribe a Report"></a>

Click **Subscribe to a Report** above to create a report subscription. 

Use this API to subscribe for reports that you want delivered over HTTP endpoint (webhooks). When you subscribe to a report, a unique subscriber id is returned to you. You’ve to use this id if you choose to unsubscribe to a report. 

+ Parameters

    + reportId : onboarding_report - This is the name of the report. 
        _Mandatory_


+ Request Subscribe to a Report (application/json)
        
    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY

    + Body

               {
                "webhookConfig": {
                "webhookUrls": [
            "string"
                    ]
                }
                }

            
+ Response 200 (application/json;charset=utf8)

    + Headers
    
            Transfer-Encoding :chunked
            Date:Tue, 27 Oct 2020 07:19:31 GMT
            X-INTERNAL-CORRELATION-ID: a755ee28-e1dd-4b0a-8b72-955f7ae8a623
            X-Application-Error-Code:  1000
            X-Application-Status-Code: 1000
            X-Application-Error-Message: Internal Error
            X-Application-Error-Description: An internal error occurred

    + Body

            {
            "reportId": "string",
            "subscriptionId": "string",
            "webhookInfo": [
                {
                    "status": "ENABLED",
                    "url": "string"
                }
                ]
            }

### Get Subscriptions [GET /report-configs/{reportId}/subscriptions/{subscriptionId}]

<a name="getsubscription" title="Get a List of Subscriptions"></a>
Click **Get Subscriptions** above to retrieve a list of your subscriptions to a report using the ID returned in the response to [the original request](#subscribereport).
    
+ Parameters

    + reportId - This is the name of the report. 
    + subscriptionId - This is the subscription id of a report.
    
+ Request Get Subscriptions (application/json)
    
    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY
            
+ Response 200 (application/json;charset=utf8)

    + Headers
    
            Transfer-Encoding :chunked
            Date:Tue, 27 Oct 2020 07:19:31 GMT
            X-INTERNAL-CORRELATION-ID: a755ee28-e1dd-4b0a-8b72-955f7ae8a623
            X-Application-Error-Code:  1000
            X-Application-Status-Code: 1000
            X-Application-Error-Message: Internal Error
            X-Application-Error-Description: An internal error occurred

    + Body

            {
                webhookConfig": {
                    "webhookUrls": [
                     “https://webhook.site/46286df1-8fc9-42df-a301-628b9e84580M,
                      https://webhook.site/46286df1-8fc9-42df-a301-628b9e84560f,
                      https://webhook.site/46286df1-8fc9-42df-a301-628b9e84510k"
                       ]
                },
               "subscriptionId": "198_onboarding_report",
               "reportId": "onboarding_report"
            }

### Unsubscribe from a Report [DELETE /report-configs/{reportId}/subscriptions/{subscriptionId}]
<a name="unsubscribereport" title="Unsubscribe a Report"></a>

Click **Unsubscribe from a Report** above to delete your subscription to a subscribed report.

+ Parameters

    + reportId : onboarding_report - This is the name of the report. 
        _Mandatory_
    + subscriptionId : This is the subscription id of a report.
    

+ Request Unsubscribe to a Report (application/json)

    + Headers

            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY
            
+ Response 204 (application/json;charset=utf8)

     + Headers
     
            Transfer-Encoding :chunked
            Date:Tue, 27 Oct 2020 07:19:31 GMT
            X-INTERNAL-CORRELATION-ID: a755ee28-e1dd-4b0a-8b72-955f7ae8a623
            X-Application-Error-Code:  1000
            X-Application-Status-Code: 1000
            X-Application-Error-Message: Internal Error
            X-Application-Error-Description: An internal error occurred

# Group Report Requests

## Submit Report [/report-requests]

### Submit a Report Request [POST /report-requests]
<a name="submitareportrequest" title="Submit a Report Request"></a>

Click **Submit a Report Request** above to submit a request for a report. You should have already subscribed to a [report](#subscribereport) to submit this request.

> **Note:** Once you submit a report request, you instantly get an API response that it is accepted. However, you will receive the actual webhook to download the report after 15 mins.


+ Request a report using a report id (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
            "intervalEndTime": 1525756289719,
            "intervalStartTime": 1525744000000,
            "reportId":"onboarding_report"
              
            }
     
+ Response 200 (application/json) 

    + Headers
    
            Transfer-Encoding :chunked
            Date:Tue, 27 Oct 2020 07:19:31 GMT
            X-INTERNAL-CORRELATION-ID: a755ee28-e1dd-4b0a-8b72-955f7ae8a623
            X-Application-Error-Code:  1000
            X-Application-Status-Code: 1000
            X-Application-Error-Message: Internal Error
            X-Application-Error-Description: An internal error occurred


    + Body

            {
              "creationTime": "2020-11-05T06:18:17.368Z",
              "reportId": "onboarding_report",
              "intervalStartTime": 1603349877760,
              "intervalEndTime": 1603349877804,
              "requestId": "5b1de372-654a-40bf-8fe7-d1412f95d68d"
             }